
alias cl='clear'

# Change directories
alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'

alias Downloads='cd ~/Downloads/'
alias dotfiles='cd ~/Dropbox/dotfiles/'
alias notes='cd ~/Dropbox/research-notes/'
alias tools='cd ~/Dropbox/research-tools/'
alias papers='cd ~/Dropbox/research-papers'
alias therapie='cd ~/Dropbox/therapie-tools'

# Package management
alias update='sudo apt update && sudo apt upgrade -y'
alias remove='sudo apt remove'

# Git commands
alias gits='git status'
alias gitl='git log --oneline --graph'
alias gita='git add'
alias gitc='git commit -m'
alias gitd='git diff'
alias gitds='git diff --staged'
alias gitr='git restore'
alias gitrs='git restore --staged'
alias gitrao='git remote add origin'
alias gitpom='git push origin main'

alias ls='ls -lhFX'
alias rm='rm -i'

alias cat='batcat'
